language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - git
            - build-essential
            - libopenmpi-dev
            - openmpi-bin
            - cmake-data
            - cmake
            - trilinos-all-dev
            - libx11-dev
            - x11proto-core-dev
            - libopenblas-dev
            - libhdf5-openmpi-dev
            # Manual Trilinos dependencies, which are bugged in 16.04
            - libmumps-dev
            - binutils-dev
            - libiberty-dev
            - libtbb-dev
            - libsuperlu-dev
            - libptscotch-dev
            # Compilers
            - g++-4.9
            - gfortran-4.9
      env:
         - MATRIX_EVAL="OMPI_CC=gcc-4.9 && OMPI_CXX=g++-4.9 && OMPI_FC=gfortran-4.9 CC=gcc-4.9 && CXX=g++-4.9 && FC=gfortran-4.9"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - git
            - build-essential
            - libopenmpi-dev
            - openmpi-bin
            - cmake-data
            - cmake
            - trilinos-all-dev
            - libx11-dev
            - x11proto-core-dev
            - libopenblas-dev
            - libhdf5-openmpi-dev
            # Manual Trilinos dependencies, which are bugged in 16.04
            - libmumps-dev
            - binutils-dev
            - libiberty-dev
            - libtbb-dev
            - libsuperlu-dev
            - libptscotch-dev
            # Compilers
            - g++-8
            - gfortran-8
      env:
         - MATRIX_EVAL="OMPI_CC=gcc-8 && OMPI_CXX=g++-8 && OMPI_FC=gfortran-8 CC=gcc-8 && CXX=g++-8 && FC=gfortran-8"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - git
            - build-essential
            - libmpich-dev
            - mpich
            - cmake-data
            - cmake
            - trilinos-all-dev
            - libx11-dev
            - x11proto-core-dev
            - libopenblas-dev
            - libhdf5-mpich-dev
            # Manual Trilinos dependencies, which are bugged in 16.04
            - libmumps-dev
            - binutils-dev
            - libiberty-dev
            - libtbb-dev
            - libsuperlu-dev
            - libptscotch-dev
            # Compilers
            - g++
            - gfortran
      env:
         - MATRIX_EVAL=""

env:
  - PATH=$PATH:$TRAVIS_BUILD_DIR/local/bin LIBRARY_PATH=$LIBRARY_PATH:$TRAVIS_BUILD_DIR/local/lib LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR/local/lib

cache: ccache

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - git clone https://github.com/erik808/jdqzpp.git
  - cd jdqzpp
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/local ..
  - make
  - make install
  - cd ../..
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - make check