language: cpp

dist: xenial
addons:
  apt:
    packages:
      - git
      - build-essential
      - gfortran
      - libopenmpi-dev
      - openmpi-bin
      - cmake-data
      - cmake
      - trilinos-all-dev
      - libx11-dev
      - x11proto-core-dev
      - libopenblas-dev
      - libhdf5-openmpi-dev
      # Manual Trilinos dependencies, which are bugged in 16.04
      - libmumps-dev
      - binutils-dev
      - libiberty-dev
      - libtbb-dev
      - libsuperlu-dev
      - libptscotch-dev

env:
  - PATH=$PATH:$TRAVIS_BUILD_DIR/local/bin LIBRARY_PATH=$LIBRARY_PATH:$TRAVIS_BUILD_DIR/local/lib LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR/local/lib

cache: ccache

install:
  - git clone https://github.com/erik808/jdqzpp.git
  - cd jdqzpp
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/local ..
  - make
  - make install
  - cd ../..
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - make check